var timer = document.getElementById ("timer");
var first_container = document.getElementById ("first_container");
var test_para = document.getElementById ("para_test");
var user_para = document.getElementById ("user_para");
var timeup = document.getElementById ("end_box");
var enclose = document.getElementById ("enclose");
var tryAgain = document.getElementById ("Try_Again");
var timeRem = 90;
var score = 0;
const totalTime = timeRem;

var show_para = function () {
    test_para.innerHTML = para;
};

var calcSpeed = function () {
    var words = user_para.value.split(" ").length;
    return (words * 60.0) / totalTime;
};

var start_timer = function () {
    var get_time = setInterval (function () {
        timeRem--;
        timer.innerHTML = "Time Rem: " + timeRem + "sec";
        if (timeRem == 0) {
            clearInterval (start_timer);
            user_para.remove();
            first_container.remove ();
            enclose.remove ();
            timer.remove ();
            document.body.appendChild (timeup);
            document.getElementById ("score").innerHTML = "Speed: " + calcSpeed() + " words per minute";
            timeup.style.display = "block";
        }
    }, 1000);
    user_para.removeEventListener ("keydown", start_timer);
};

var start = function () {
    timer.innerHTML = "Time Rem: " + timeRem + "sec";
    test_para.value = "";
    show_para ();
    user_para.addEventListener ("keydown", start_timer);
};

var para = "Hardly any important changes in frequency take place on a large distribution system except during a major disturbance. However, large frequency changes often take place on isolated, lowpower systems in which electric energy is generated by means of diesel engines or gas turbines.Examples of such systems are : emergency supply in a hospital and the electrical system on a ship etc.The major effect of change in supply frequency is on motor speed. If frequency drops by 10%,then motor speed also drops by 10%.  Machine tools and other motor-driven equipment meant for 50Hz causes problem when connected to 60-Hz supply. Everything runs (60 − 50) × 100/50 = 20% faster than normal and this may not be acceptable in all applications. In that case, we have to use either gears to reduce motor speed or an expensive 50-Hz source";

start ();

tryAgain.addEventListener ("click", function (){
    window.location.reload ();
});